language: perl
matrix:
  include:
    - perl: "5.8"
      dist: trusty
    - perl: "5.10"
      dist: trusty
    - perl: "5.30"
install:
  - curl -fsSL --compressed https://git.io/cpm | perl - install -g --with-develop --with-recommends
script:
  - prove -l t
